# action.yml
name: "Akash On Github Actions"
description: "Akash CLI Tools in GitHub. Publish a Project."
inputs:
  AKASH_WALLET_KEY: # id of input
    description: "list of secrets to load"
    required: true
  AKASH_WALLET_KEY_PASSWORD: # id of input
    description: "list of secrets to load"
    required: true
  GITHUB_TOKEN: # id of input
    description: "github token"
    required: true
  AKASH_DEPLOY_CERTIFICATE:
    description: "github token"
    required: true
  AKASH_FROM:
    description: "github token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Akash CLI
      shell: bash
      run: |-
        wget $(curl -H "Authorization: token ${{inputs.GITHUB_TOKEN}}" -s https://api.github.com/repos/ovrclk/akash/releases/latest | jq -r ".assets[] | select(.name | test(\"linux_amd64.deb\")) | .browser_download_url") -O akash.deb
        sudo dpkg -i akash.deb
        wget $(curl -H "Authorization: token ${{inputs.GITHUB_TOKEN}}" -s https://api.github.com/repos/ovrclk/e2e-production/releases/latest | jq -r ".assets[] | select(.name | test(\"linux_amd64.deb\")) | .browser_download_url") -O e2e.deb
        sudo dpkg -i e2e.deb
    - name: import key
      shell: bash
      env:
        AKASH_HOME: /home/runner/.akash
      run: |-
        echo "${{inputs.AKASH_WALLET_KEY}}" > key.key
        echo "${{inputs.AKASH_WALLET_KEY_PASSWORD}}" | akash keys import ${{inputs.AKASH_FROM}} key.key --keyring-backend test
    - name: import certificate
      env:
        AKASH_HOME: /home/runner/.akash
      shell: bash
      run: echo "${{inputs.AKASH_DEPLOY_CERTIFICATE}}" > ${{env.AKASH_HOME}}/$(akash keys show ${{inputs.AKASH_FROM}} --output=json | jq -r ".address").pem
