# action.yml
name: "Akash On Github Actions"
description: "Akash CLI Tools in GitHub. Publish a Project."
inputs:
  walletkey: # id of input
    description: "list of secrets to load"
    required: true
  walletkeypass: # id of input
    description: "list of secrets to load"
    required: true
  GITHUB_TOKEN: # id of input
    description: "github token"
    required: true
runs:
  using: "composite"
  steps:
    - run: |-
        wget $(curl -H "Authorization: token ${{inputs.GITHUB_TOKEN}}" -s https://api.github.com/repos/ovrclk/akash/releases/latest | jq -r ".assets[] | select(.name | test(\"linux_amd64.deb\")) | .browser_download_url") -O akash.deb
        sudo dpkg -i akash.deb
        wget $(curl -H "Authorization: token ${{inputs.GITHUB_TOKEN}}" -s https://api.github.com/repos/ovrclk/e2e-production/releases/latest | jq -r ".assets[] | select(.name | test(\"linux_amd64.deb\")) | .browser_download_url") -O e2e.deb
        sudo dpkg -i e2e.deb
      shell: bash
