# action.yml
name: "Akash On Github Actions"
description: "Akash CLI Tools in GitHub. Publish a Project."
inputs:
  walletkey: # id of input
    description: "list of secrets to load"
    required: true
  walletkeypass: # id of input
    description: "list of secrets to load"
    required: true
outputs:
  cli-version: # id of output
    description: "The version of the CLI running"
  network:
    description: "The network that the job is attached to"
  network-version:
    description: "The version of the Akash Network"
  network-node:
    description: "The network RPC node the job is using for chain communicating"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    WALLET_KEY: ${{ inputs.walletkey }}
    WALLET_KEY_PASS: ${{ inputs.walletkeypass }}
